# Generated by Django 4.0.2 on 2022-02-17 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewsetclasses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drugcategory',
            options={'ordering': ('name',), 'verbose_name_plural': 'Drug categories'},
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
