# Generated by Django 4.0.2 on 2022-02-15 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('functions', '0002_herbs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Herbs',
            new_name='Herb',
        ),
    ]
